// Generated by Xata Codegen 0.26.7. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
    BaseClientOptions,
    SchemaInference,
    XataRecord,
} from "@xata.io/client";

const tables = [
    {
        name: "transactions",
        columns: [
            { name: "amount", type: "float" },
            { name: "name", type: "string" },
            { name: "section_id", type: "string" },
        ],
    },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Transactions = InferredTypes["transactions"];
export type TransactionsRecord = Transactions & XataRecord;

export type DatabaseSchema = {
    transactions: TransactionsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
    databaseURL: "https://main-sv67m5.us-west-2.xata.sh/db/budget-keeper",
};

    export class XataClient extends DatabaseClient<DatabaseSchema> {
        constructor(options?: BaseClientOptions) {
            super({ ...defaultOptions, ...options }, tables);
        }
    }

    let instance: XataClient | undefined = undefined;

    export const getXataClient = () => {
        if (instance) return instance;

        instance = new XataClient();
        return instance;
    };
